/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.form;

import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import raven.tabbed.TabbedForm;

/**
 *
 * @author jahir
 */
public class TestForm extends TabbedForm {

    /**
     * Creates new form TestForm3
     */
    
    
    private int tam;
    private int n = -1;
    private int[] elemento ;
    private int contador = 1;
    private static boolean bloqueado = false;

    public TestForm() {
        initComponents();
        panelAgg.setVisible(false);
        if (bloqueado){
                jButton1.setEnabled(false);
                tamarray.setEnabled(false);
                
                }
        info.setVisible(false);
        exitInfo.setVisible(false);
        
        validarCampo(tamarray, texto -> texto.matches("\\d+"));
        
        
        
    }
    
    private void validarCampo(javax.swing.JTextField campo, java.util.function.Predicate<String> condicion) {
    campo.getDocument().addDocumentListener(new DocumentListener() {
        private void validar() {
            String texto = campo.getText();
            if (texto.isEmpty()) {
                campo.putClientProperty(FlatClientProperties.OUTLINE, null); // sin borde
            } else if (!condicion.test(texto)) {
                campo.putClientProperty(FlatClientProperties.OUTLINE, "error"); // borde rojo
            } else {
                campo.putClientProperty(FlatClientProperties.OUTLINE, "success"); // borde verde
            }
            campo.repaint();
        }

        @Override
        public void insertUpdate(DocumentEvent e) { validar(); }

        @Override
        public void removeUpdate(DocumentEvent e) { validar(); }

        @Override
        public void changedUpdate(DocumentEvent e) { validar(); }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tam = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tamarray = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        info = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        exitInfo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelAgg = new javax.swing.JPanel();
        elementoo = new javax.swing.JLabel();
        bntAgregar = new javax.swing.JButton();
        integrar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese el tamano del arreglo");

        tamarray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamarrayActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raven/image/manual ligth (1).png"))); // NOI18N

        jButton2.setText("Como usarlo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exitInfo.setText("X");
        exitInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitInfoActionPerformed(evt);
            }
        });

        elementoo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        elementoo.setText("Ingrese el elemento ");

        bntAgregar.setText("Enviar");
        bntAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarActionPerformed(evt);
            }
        });

        integrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAggLayout = new javax.swing.GroupLayout(panelAgg);
        panelAgg.setLayout(panelAggLayout);
        panelAggLayout.setHorizontalGroup(
            panelAggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAggLayout.createSequentialGroup()
                .addComponent(elementoo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(integrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(panelAggLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(bntAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAggLayout.setVerticalGroup(
            panelAggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAggLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelAggLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementoo)
                    .addComponent(integrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton3.setText("Informacion del ejercicio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reiniciar programa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelAgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(302, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(110, 110, 110)))
        );

        javax.swing.GroupLayout TamLayout = new javax.swing.GroupLayout(Tam);
        Tam.setLayout(TamLayout);
        TamLayout.setHorizontalGroup(
            TamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TamLayout.createSequentialGroup()
                .addGroup(TamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TamLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TamLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(TamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TamLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(93, 93, 93)
                                .addComponent(tamarray, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TamLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(TamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        TamLayout.setVerticalGroup(
            TamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TamLayout.createSequentialGroup()
                .addGroup(TamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TamLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(TamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tamarray, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TamLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(exitInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TamLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void integrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_integrarActionPerformed

    private void bntAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarActionPerformed
        // TODO add your handling code here:

        try {
            if (integrar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
            } else {
                int elementoA = Integer.parseInt(integrar.getText());
                int antes = n;
                n = LogicaLab2.alta(elemento, n, tam, elementoA);

                // Si realmente se insertó (n cambió)
                if (n != antes) {
                    if (n < tam - 1) {
                        elementoo.setText("Ingrese el elemento: " + (n + 2));
                        // n empieza en -1, así que +2 muestra el número de elemento humano
                    } else {
                        integrar.setText("");
                        elementoo.setText("Ingrese el elemento: sin espacios");
                        integrar.setEnabled(false);
                        bntAgregar.setEnabled(false);

                        System.err.println("elemento 1" + elemento[0]);
                        System.out.println("elemento 2" +elemento[1]);
                        System.out.println("elemento 3" +elemento[2]);
                        System.out.println("elemento 4" +elemento[3]);
                        System.out.println("elemento 5" +elemento[4]);
                    }
                }

                // limpiar campo si sigue activo
                if (integrar.isEnabled()) {
                    integrar.setText("");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ser un número entero.");
        }
    }//GEN-LAST:event_bntAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            if (tamarray.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
            } else {
                int B = Integer.parseInt(tamarray.getText()); // mover aquí
                if (B > 0) {
                    tam = B;
                    elemento = new int[tam];
                    JOptionPane.showMessageDialog(this, "Tamaño agregado correctamente.");

                    bloqueado = true;
                    jButton1.setEnabled(false);
                    tamarray.setEnabled(false);

                    // limpiar campos
                    tamarray.setText("");
                    panelAgg.setVisible(true);
                    integrar.setEnabled(true);
                    bntAgregar.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Tamaño debe ser mayor a 0");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe ser un número entero.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tamarrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamarrayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamarrayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        info.setVisible(true);
                        exitInfo.setVisible(true);

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exitInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitInfoActionPerformed
        // TODO add your handling code here:
                info.setVisible(false);
                exitInfo.setVisible(false);

    }//GEN-LAST:event_exitInfoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Utilizando modo grafico hacer una interfaz que permita ingresar datos en arreglos (el tamaño" +
"deberá ser definido por el usuario), posteriormente seleccionar con el método con el que se" +
"desea ordenar el arreglo o hacer una búsqueda en el arreglo." +
"La interfaz deberá de tener dos botones de comando: uno que permita realizar ordenación y" +
"el otro para la búsqueda.\n" +
"Cuando se seleccione el de ordenación deberá aparecer otra interfaz que me permita" +
"seleccionar cualquiera de los 6 métodos de ordenación estudiados. Una vez seleccionado el" +
"método se debe de leer el arreglo (esto se debe hacer dentro de cada método) y deberán" +
"imprimir el arreglo tal y como fue leído e imprimir el arreglo ya ordenado. Deberá de tener" +
"una opción que permita regresar a la interfaz anterior (Interfaz de ordenación y búsqueda).\n" +
"Cuando se seleccione la opción de búsqueda, el usuario deberá leer el arreglo (recordar" +
"ordenar el arreglo con cualquiera de los métodos de ordenación) y solicitar el dato a buscar," +
"el método deberá mostrar la posición en la que se encuentra el dato buscado o un mensaje" +
"que diga que el dato no se encontró. Deberá de tener una opción que permita regresar a la" +
"interfaz anterior (Interfaz de ordenación y búsqueda).\n" +
"Se deberá hacer un método de lectura de arreglo, el cual deberá de ser llamado por todos" +
"los métodos tanto los de ordenación como los de búsqueda cada vez que se necesite leer un" +
"arreglo.\n" +
"Esta interfaz de los métodos de ordenación y búsqueda deberá implementar la POO para" +
"mayor visualización y pureza de su código fuente.\n" +
"También esta interfaz deberá de tener un botón de regresar, para regresar el control a la" +
"primera interfaz (Presentación del trabajo de la guía de laboratorio 2).");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        bloqueado = false;
        jButton1.setEnabled(true);
        tamarray.setEnabled(true);
        panelAgg.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tam;
    private javax.swing.JButton bntAgregar;
    private javax.swing.JLabel elementoo;
    private javax.swing.JButton exitInfo;
    private javax.swing.JLabel info;
    private javax.swing.JTextField integrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelAgg;
    private javax.swing.JTextField tamarray;
    // End of variables declaration//GEN-END:variables
}
